Repository StudentTraineeCenter/zpevnicek, pull requests merged in 2023-03, with the labels that each got.

#144 Add the prebuild command
  README.md
Labels: enhancement

#146 Dependency updates
  .gitignore
  .gitpod.yml
  .node-version
  README.md
  package.json
  yarn.lock
Labels: dependencies

#149 New songs
  _songs/andel-karel-kryl.json
  _songs/california-dreaming-the-mamas-&-the-papas.json
  _songs/cecilia-simon-&-garfunkel.json
  _songs/day-tripper-the-beatles.json
  _songs/fortunate-son-creedence-clearwater-revival.json
  _songs/jdou-po-mne-jdou-jaromir-nohavica.json
  _songs/jo-tresne-zraly-waldemar-matuska.json
  _songs/malovani-divokej-bill.json
  _songs/nad-stadem-koni-buty.json
  _songs/never-gonna-give-you-up-rick-astley.json
  _songs/san-francisco-scott-mckenzie.json
  _songs/slunecny-hrob-blue-effect.json
  _songs/stand-by-me-oasis.json
  _songs/wholl-stop-the-rain-creedence-clearwater-revival.json
  _songs/wonderwall-oasis.json
  _songs/zelva-olympic.json
  _songs/zombie-the-cranberries.json
Labels: content
